<h1>Regression</h1>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
def initialize_parameter(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1,L):
        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l],1))

    return parameters

In [5]:
def  linear_forwrd(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b
    return Z

In [6]:
#forward propogation fn

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forwrd(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)
          
  return A,A_prev

In [7]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no. of features, no. of training example)
y = df[['lpa']].values[0][0]

In [8]:
X

array([[8],
       [8]], dtype=int64)

In [9]:
y

4

In [10]:
parameters = initialize_parameter([2,2,1])

In [11]:
y_hat, A1 = L_layer_forward(X, parameters)

In [12]:
y_hat = y_hat[0][0]

In [13]:
A1

array([[1.6],
       [1.6]])

In [14]:
(y - 0.32)**2

13.5424

In [15]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [16]:
update_parameters(parameters, y, y_hat, A1, X)

In [17]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [18]:
# epochs implementation

parameters = initialize_parameter([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1)      # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

<h1>Same implementation using Keras</h1>

In [20]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [21]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [47]:
X = df[['cgpa', 'profile_score']].values
y = df[['lpa']].values.reshape(-1, 1)
X,y

(array([[ 8,  8],
        [ 7,  9],
        [ 6, 10],
        [ 5, 12]], dtype=int64),
 array([[4],
        [5],
        [6],
        [7]], dtype=int64))

In [45]:
y.shape

(4, 1)

In [48]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

C:\Users\Animesh\miniconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [49]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [50]:
model.get_weights()

[array([[ 0.38642287,  0.24543202],
        [-1.0399075 , -0.32434672]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.07027733],
        [1.0247129 ]], dtype=float32),
 array([0.], dtype=float32)]

In [51]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype= np.float32), 
               np.array([0., 0.], dtype= np.float32),
               np.array([[0.1], [0.1]], dtype= np.float32),
                np.array([0.], dtype= np.float32)]

In [52]:
model.set_weights(new_weights)

In [53]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [54]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mse', optimizer=optimizer)

In [55]:
model.fit(X, y, epochs= 75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 25.4431
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 30.7799
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 30.5718
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 32.1126
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 26.1978
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 21.1921
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 20.8670
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.2275
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 21.7459
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 28.3431
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 27.8879
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 24.1057
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 22.3141
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 22.5808
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 18.6502
Epoch 16/75
4/4 ━━━

In [56]:
model.get_weights()

[array([[0.37338585, 0.37338585],
        [0.36546975, 0.36546975]], dtype=float32),
 array([0.2721212, 0.2721212], dtype=float32),
 array([[0.3727316],
        [0.3727316]], dtype=float32),
 array([0.20465961], dtype=float32)]