<h1>Classification</h1>

In [1]:
import numpy as np
import pandas as pd

In [10]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,12,0]], columns=['cgpa','profile_score','placed'])
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5             12       0

In [17]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1,L):
        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l],1))

    return parameters

In [18]:
# Utility Functions
def sigmoid(Z):
    A = 1/(1+np.exp(-Z))
    return A

In [19]:
def linear_forward(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b
    A = sigmoid(Z)
    return A

In [20]:
# L-layer feed forward

def L_layer_forward(X, parameters):
    A = X
    L = len(parameters) // 2                  # number of layers in the neural network
  
    for l in range(1, L+1):
        A_prev = A 
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        #print("A"+str(l-1)+": ", A_prev)
        #print("W"+str(l)+": ", Wl)
        #print("b"+str(l)+": ", bl)
        #print("--"*20)

        A = linear_forward(A_prev, Wl, bl)
        #print("A"+str(l)+": ", A)
        #print("**"*20)
          
    return A,A_prev


In [21]:
def update_parameters(parameters,y,y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [22]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)      #Shape(no. of features, no. of training example)
y = df[['placed']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.613402628898913


{'W1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [23]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.568725622654268


{'W1': array([[0.10000937, 0.10001059],
        [0.10000937, 0.10001059]]),
 'b1': array([[1.24770113e-06],
        [1.24770113e-06]]),
 'W2': array([[0.10007424],
        [0.10007424]]),
 'b2': array([[0.10011761]])}

In [24]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.8353333695154365


{'W1': array([[0.10000463, 0.10000267],
        [0.10000463, 0.10000267]]),
 'b1': array([[4.56125378e-07],
        [4.56135584e-07]]),
 'W2': array([[0.10002712],
        [0.10002712]]),
 'b2': array([[0.09997049]])}

In [25]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.8367359874723076


{'W1': array([[0.10000092, 0.09999379],
        [0.10000092, 0.09999379]]),
 'b1': array([[-2.84055419e-07],
        [-2.84062197e-07]]),
 'W2': array([[0.09997919],
        [0.09997919]]),
 'b2': array([[0.0999225]])}

In [36]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['placed']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.7135494021352312
Epoch -  2 Loss -  0.7023979867791279
Epoch -  3 Loss -  0.702393772800165
Epoch -  4 Loss -  0.7023895608076378
Epoch -  5 Loss -  0.7023853508005624
Epoch -  6 Loss -  0.7023811427779558
Epoch -  7 Loss -  0.7023769367388353
Epoch -  8 Loss -  0.7023727326822189
Epoch -  9 Loss -  0.7023685306071253
Epoch -  10 Loss -  0.7023643305125733
Epoch -  11 Loss -  0.7023601323975824
Epoch -  12 Loss -  0.7023559362611727
Epoch -  13 Loss -  0.7023517421023647
Epoch -  14 Loss -  0.7023475499201793
Epoch -  15 Loss -  0.7023433597136384
Epoch -  16 Loss -  0.7023391714817637
Epoch -  17 Loss -  0.702334985223578
Epoch -  18 Loss -  0.7023308009381042
Epoch -  19 Loss -  0.7023266186243662
Epoch -  20 Loss -  0.7023224382813881
Epoch -  21 Loss -  0.7023182599081943
Epoch -  22 Loss -  0.70231408350381
Epoch -  23 Loss -  0.7023099090672611
Epoch -  24 Loss -  0.7023057365975736
Epoch -  25 Loss -  0.7023015660937743
Epoch -  26 Loss -  0.7022973975548902

{'W1': array([[0.10003318, 0.09967885],
        [0.1000332 , 0.09967816]]),
 'b1': array([[-1.57001680e-05],
        [-1.57367755e-05]]),
 'W2': array([[0.098865  ],
        [0.09886551]]),
 'b2': array([[0.0988089]])}

<h1>Same implementation using Keras</h1>

In [27]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [28]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5             12       0

In [46]:
X = df[['cgpa', 'profile_score']].values
y = df[['placed']].values.reshape(-1, 1)
X,y

(array([[ 8,  8],
        [ 7,  9],
        [ 6, 10],
        [ 5, 12]], dtype=int64),
 array([[1],
        [1],
        [0],
        [0]], dtype=int64))

In [48]:
X.shape

(4, 2)

In [37]:
model = Sequential()

model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

C:\Users\Animesh\miniconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [38]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.get_weights()

[array([[ 0.19835663,  0.01561272],
        [-0.5791441 , -0.3077867 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.09765828],
        [0.210886  ]], dtype=float32),
 array([0.], dtype=float32)]

In [40]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype= np.float32), 
               np.array([0., 0.], dtype= np.float32),
               np.array([[0.1], [0.1]], dtype= np.float32),
                np.array([0.], dtype= np.float32)]

In [41]:
model.set_weights(new_weights)

In [42]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [49]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='bce', optimizer=optimizer)

In [50]:
model.fit(X, y, epochs= 50, verbose=1, batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.7084
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6751
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.6858
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.7349
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.6754
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6859
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.7071
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6753
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6859
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7072
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6600
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7066
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6602
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.6755
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.7322
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━

In [51]:
model.get_weights()

[array([[0.11558794, 0.11558794],
        [0.06074373, 0.06074373]], dtype=float32),
 array([-0.01493776, -0.01493776], dtype=float32),
 array([[0.08590855],
        [0.08590855]], dtype=float32),
 array([-0.01438245], dtype=float32)]